project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - lecture1.qmd
    - lecture2.qmd
    - lecture3.qmd
    - lecture4.qmd
    - lecture5.qmd
    - lecture6.qmd
    - lecture7.qmd
    - slides.qmd

  resources: 
    - CNAME
    - Slides1_IntroToML.pdf
    - RandomMatrixTheory.pdf
    - NeuralNetworksAndNTK.pdf
    - AdvancedKernels.pdf
   
    

    
website:
  title: "Semyon Malamud Lectures"
  search: false
  page-navigation: true  
  
format:
  html:
    theme:
      light: flatly
      dark: superhero

    



