## {style="text-align: center;"} Lecture 7: Bayesian Learning, Gaussian Processes and Equilibrium Models in High Dimensions

In this closing lecture, we show how the techniques developed in the previous lectures can be used to study equilibria where agents use complex models. We show how Bayesian learning becomes tractable and exhibits striking hidden order in high dimensions. We then show how embedding Bayesian agents in standard equilibrium models allows us to study parameter learning in environments previously considered intractable. We also show how one can use these methods in non-parametric learning and establish surprising connections with Gaussian Processes. We discuss the surprising phenomena occurring in models where agents (like real-world humans) try to interpolate based on past observations.

## Key References

- Farmer, Leland E, Emi Nakamura, and Jon Steinsson, "Learning about the long run," *Journal of Political Economy*, 2024, 132 (10), 3334–3377.

- Moll, Benjamin, "The Trouble with Rational Expectations in Heterogeneous Agent Models: A Challenge for Macroeconomics," London School of Economics, mimeo, available at https://benjaminmoll.com, 2024.

- Molavi, Pooya, Alireza Tahbaz-Salehi, and Andrea Vedolin. "Model complexity, expectations, and asset prices." *Review of Economic Studies* 91, no. 4 (2024): 2462-2507.